Feature DSL
PPS-22-Scooby/PPS-22-Scooby pull request #53
Opened 2024-07-23 20:23 UTC by v4l3rio

implemented the first version of dsl

2024-07-23 20:32 UTC, giovaz94 requested changes
Missing docs in all the features. 
Also I think a refactoring is necessary in order to merge to develop

2024-07-23 20:36 UTC, Luca1313 approved these changes

2024-07-27 09:29 UTC, giovaz94 approved these changes
All ok for me. 
Very Nice 👍

2024-07-27 09:35 UTC, FreshMag approved these changes

2024-07-27 09:40 UTC, merged